In [8]:
# 游戏

from pulp import LpMaximize, LpProblem, LpVariable, lpSum, value
#pulp库是用python语言实现的线性规划、整数规划、求解器、优化器的集合。
#LpMaximize表示目标方向为最大化，LpProblem表示建立一个线性规划问题，LpVariable表示决策变量，lpSum表示求和函数,value()函数用于求解变量的值。

# 创建一个最大化问题
problem=LpProblem("Maximize_Experience",LpMaximize)  # 定义问题,包括问题名和目标方向

# 定义决策变量
x1=LpVariable('x1',lowBound=0,cat='Integer') #A图通关次数,cat='Integer'表示变量只能取整数值
x2=LpVariable('x2',lowBound=0,cat='Integer') #B图通关次数
x3=LpVariable('x3',lowBound=0,cat='Integer') #C图通关次数

# 定义目标函数
problem+=20*x1+30*x2+40*x3, "Total_Experience"

# 添加约束条件
problem+=4*x1+8*x2+10*x3<=100,"Resource_Constraint"
problem+=x1+x2+x3<=20,'Time_Constraint'

# 解决问题
problem.solve()

# 输出结果
print("A,B,C三图分别通关次数为:")
print(int(value(x1)),int(value(x2)),int(value(x3)))# value()函数用于求解变量的值

print("总体经验值为:",int(value(problem.objective)))# problem.objective表示目标函数的值


A,B,C三图分别通关次数为:
17 0 3
总体经验值为: 460


In [9]:
%pip install pulp


Note: you may need to restart the kernel to use updated packages.


In [16]:
# 背包问题
from pulp import LpMaximize, LpProblem, LpVariable, lpSum, value

# 创建最大化问题
problem=LpProblem("Knapsack_Problem",LpMaximize)

# 定义目标函数系数(利润)
profit=[540,200,180,350,60,150,280,450,320,120]

# 定义约束系数(重量)
weights=[6,3,4,5,1,2,3,5,4,2]
max_weight=30

# 定义决策变量(0-1变量)
x=[LpVariable(f"x{i+1}",cat='Binary') for i in range(10)]# 索引,建立了列表x，元素为LpVariable对象
problem+=lpSum(profit[i]*x[i] for i in range(10)),'Total_Profit'
print(x)
print(x[0])
print(x[1])

# 添加约束条件
problem+=lpSum(weights[i]*x[i] for i in range(10))<=max_weight,'Weight_Constraint'

# 求解问题
problem.solve()

# 输出结果
print('选中的物品是:(1代表选中，0代表不选中)')
selected_items=[int(value(x[i])) for i in range(10)]
print(selected_items)
print('最大利润为:',value(problem.objective))

[x1, x2, x3, x4, x5, x6, x7, x8, x9, x10]
x1
x2
选中的物品是:(1代表选中，0代表不选中)
[1, 1, 0, 1, 0, 1, 1, 1, 1, 1]
最大利润为: 2410.0


In [23]:
# 指派
from pulp import LpMaximize, LpProblem, LpVariable, lpSum, value

# 创建问题
problem=LpProblem("0-1 LNP",LpMaximize)

# 定义目标函数系数(泳姿时间)
c=[66.8,75.6,87,58.6,57.2,66,66.4,53,78,67.8,84.6,59.4,
   70,74.2,69.6,57.2,67.4,71,83.8,62.4]

# 定义变量
x=[LpVariable(f"x{i+1}",cat='Integer') for i in range(20)]

# 定义目标函数(最小化总时间)
problem+=lpSum(c[i]*x[i] for i in range(20)),'Total_Time'

# 添加不等式约束
A=[
    [1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1],
]
b=[1,1,1,1,1]
for i in range(len(A)):
    problem+=lpSum(A[i][j]*x[j] for j in range(20))<=b[i],f"Person_Constraint_{i+1}"

# 添加等式约束
Aeq=[
    [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
    [0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0],
    [0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0],
    [0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1],
]
beq=[1,1,1,1]
for i in range(len(Aeq)):
    problem+=lpSum(Aeq[i][j]*x[j] for j in range(20))==beq[i],f"Person_Equality_Constraint_{i+1}"

# 求解
problem.solve()

# 输出结果
print('分配结果(0表示不分配，1表示分配)')
assignment=[int(value(x[i])) for i in range(20)]
print(assignment)
print('最小总时间:',value(problem.objective))


# 输出结果重塑为矩阵形式
import numpy as np
assignment_matrix=np.array(assignment).reshape(4,5)
print('分配结果矩阵形式:')
print(assignment_matrix)


分配结果(0表示不分配，1表示分配)
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
最小总时间: 315.8
分配结果矩阵形式:
[[0 0 0 1 1]
 [0 0 0 0 0]
 [0 1 0 0 1]
 [0 0 1 0 0]]
