In [3]:
import numpy as np

#定义一个mylog函数,用于计算log值
def mylog(p):
    n=len(p)
    lnp=np.zeros(n)
    for i in range(n):
        if p[i]==0:
            lnp[i]=0
        else:
            lnp[i]=np.log(p[i])
    return lnp

In [4]:
#定义指标矩阵
X=np.array([[9,0,0,0],[8,3,0.9,0.5],[6,7,0.2,1]])

#对矩阵X进行标准化处理,得到标准化矩阵Z
Z=X/np.sqrt(np.sum(X*X,axis=0))

print("标准化矩阵Z= ")
print(Z)

#计算熵权所需变量和矩阵初始化
n,m=Z.shape  #n为样本数,m为指标数
D=np.zeros(m)  #初始化一个长度为m的数组D,用于保存每个指标点信息效用值

#计算每个指标的信息效用值
for i in range(m):
    x=Z[:,i]  #获取Z的第i列,即第i个指标的所有数据
    p=x/np.sum(x)  #计算第i个指标的概率分布
    e=-np.sum(p*mylog(p))/np.log(n)   #计算信息熵e
    D[i]=1-e  

W=D/np.sum(D)  #将信息效用值D归一化,得到个指标熵权

print("指标熵权W= ")
print(W)

Y = Z * np.tile(W, (n, 1))
print('加权指标矩阵Y=')
print(Y)

# 求和，得到各个指标的加权值
weighted_sums = np.sum(Y, axis=1)
print('各个指标的加权值:')
print(weighted_sums)


标准化矩阵Z= 
[[0.66896473 0.         0.         0.        ]
 [0.59463532 0.3939193  0.97618706 0.4472136 ]
 [0.44597649 0.91914503 0.21693046 0.89442719]]
指标熵权W= 
[0.00856537 0.30716152 0.39326471 0.2910084 ]
加权指标矩阵Y=
[[0.00572993 0.         0.         0.        ]
 [0.00509327 0.12099685 0.38389992 0.13014291]
 [0.00381996 0.28232598 0.08531109 0.26028583]]
各个指标的加权值:
[0.00572993 0.64013295 0.63174286]
